config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins, controllers: {
    sessions: 'admin/sessions',
    registrations: 'admin/registrations'
  }
  
  devise_for :customers, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }
  
  namespace :admin do
    get '/top' => 'homes#top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show]
  end
  
  
  get '/' => 'public/homes#top'
  root to: "public/homes#top"
  get 'about' => 'public/homes#about'
  
  scope module: 'public' do
    resources :items, only: [:index, :show,]
    get '/mypage' => 'customers#show'
    get '/mypage/edit' => 'customers#edit'
    patch '/mypage/edit' => 'customers#update'
    get 'customers//status' => 'customers#status', as: 'customer_status'
    patch 'customers/change' => 'customers#change', as: 'change_status'
    resources :cart_items, only: [:index, :update, :create]
    delete 'cart_item/:id' => 'cart_items#destroy', as: 'destroy_cart_item'
    delete 'cart_items' => 'cart_items#destroy_all', as: 'destroy_cart_items'
    resources :orders, only: [:new, :create, :index, :show]
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/decision' => 'orders#decision'
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    
    belongs_to :customer
    
    validates :name, presence: true
    validates :postal_code, presence: true
    validates :address, presence: true
    
    def select_name
       "〒" + postal_code + " " + address + " " + name
    end
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    
    belongs_to :customer
    belongs_to :item
    
    validates :amount, presence: true
    
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/item.rb
class Item < ApplicationRecord
    
    has_many :cart_items, dependent: :destroy
    has_many :order_items, dependent: :destroy
    
    attachment :image
    
    enum is_active: {販売中:0, 販売停止:1, 売切れ:2}
    
end

app/models/order.rb
class Order < ApplicationRecord
    
    has_many :order_items, dependent: :destroy
    belongs_to :customer
    
    enum payment_option: {クレジットカード:0, 銀行振込:1}
    enum is_active: {入金待ち:0}
    
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    
    belongs_to :order
    belongs_to :item
    
    enum is_active: {製作待ち:0}
    
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
    
    def index
        @customers = Customer.page(params[:page]).per(7).reverse_order
    end
    
    def show
        @customer = Customer.find(params[:id])
    end
    
    def edit
        @customer = Customer.find(params[:id])
    end
    
    def update
        @customer = Customer.find(params[:id])
        @customer.update(customer_params)
        redirect_to admin_customer_path(@customer.id)
      
    end
    
    private
    
    def customer_params
        params.require(:customer).permit(:last_name,
                                         :first_name,
                                         :last_name_kana,
                                         :first_name_kana,
                                         :email,
                                         :telephone_number,
                                         :postal_code,
                                         :address,
                                         :is_active)
    end
    
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
    
    def index
        @genres = Genre.page(params[:page]).per(5).reverse_order
        @genre = Genre.new
    end
    
    def create
        @genre = Genre.new(genre_params)
        @genre.save
        redirect_to admin_genres_path
    end
    
    def edit
        @genre = Genre.find(params[:id])
    end
    
    def update
        @genre = Genre.find(params[:id])
        @genre.update(genre_params)
        redirect_to admin_genres_path
    end
    
    private
    
    def genre_params
        params.require(:genre).permit(:name,
                                     :created_at,
                                     :updated_at)
    end
    
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    
    def top
        @orders = Order.page(params[:page]).per(6).reverse_order
    end
    
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    
    def index
        @items = Item.page(params[:page]).per(10).reverse_order
    end

    def new
        @item = Item.new
    end
    
    def create
        @item = Item.new(item_params)
        @item.save
        redirect_to admin_item_path(@item)
    end
    
    def show
        @item = Item.find(params[:id])
    end
    
    def edit
        @item = Item.find(params[:id])
    end
    
    def update
        @item = Item.find(params[:id])
        if params[:item][:active_option] == "0"
            @item.is_active = 0
        elsif params[:item][:active_option] == "1"
            @item.is_active = 1
        elsif params[:item][:active_option] == "2"
            @item.is_active = 2
        end
        @item.update(item_params)
        redirect_to admin_item_path(@item.id)
    end
    
    private
    
    def item_params
        params.require(:item).permit(:name, :introduction, :image, :price, :is_active)
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    
    
    

    protected
    
    def set_customer
        @id = current_customer.id
    end
    
    def set_shipping
        @shipping = 800
    end
    
    def set_tax
        @tax = 1.1
    end
    
    def configure_permitted_parameters
        if resource_class == Customer
            devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name,
                                                               :first_name,
                                                               :last_name_kana,
                                                               :first_name_kana,
                                                               :telephone_number,
                                                               :postal_code,
                                                               :address,
                                                               :is_activ])
            devise_parameter_sanitizer.permit(:sign_in,keys: [:email])
            devise_parameter_sanitizer.permit(:account_update,keys: [:last_name,
                                                                    :first_name,
                                                                    :last_name_kana,
                                                                    :first_name_kana,
                                                                    :telephone_number,
                                                                    :postal_code,
                                                                    :address,
                                                                    :is_active])
        elsif resource_class == Admin
            devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
            devise_parameter_sanitizer.permit(:sign_in,keys: [:email])
            devise_parameter_sanitizer.permit(:account_update,keys: [:name,:email])
        end
    end
    
    private
    
    def after_sign_up_path_for(resource)
        mypage_path(resource)
    end
    
    def after_sign_in_path_for(resource)
        case resource
            when Admin
              admin_top_path          
            when Customer
              root_path              
        end
    end
    
    def after_sign_out_path_for(resource_or_scope)
        if resource_or_scope == :admin
            new_admin_session_path
        else
            new_customer_session_path
        end
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2 offset-md-1 bg-danger">
          <h3 class="mt-5  bg-light rounded-pill text-center">会員情報編集</h3> 
        </div>
        <div class="col-md-8 pt-5">
            <div>
                <%= form_with model: [:admin, @customer], local: true do |f| %>
                    <table class="table">
                        <tr>
                            <th>
                                <label for="inputName">氏名</label>
                            </th>
                            <td class="d-flex flex-row">
                                <%= f.text_field :last_name, class:"mr-4", autofocus: true, id:"inputLastName", placeholder: "姓" %>
                                <%= f.text_field :first_name, autofocus: true, id:"inputFirstName", placeholder: "名" %>
                            </td>
                        </tr>
                        <tr>
                            <th>
                                <label for="inputNameKana">フリガナ</label>
                            </th>
                            <td>
                                <%= f.text_field :last_name_kana, class:"mr-4", autofocus: true, id:"inputLastNameKana", placeholder: "セイ" %>
                                <%= f.text_field :first_name_kana, autofocus: true, id:"inputFirstNameKana", placeholder: "メイ" %>
                            </td>
                        </tr>
                        <tr>
                            <th><label for="inputPostalCode">郵便番号</label></th>
                            <td><%= f.text_field :postal_code, autofocus: true, id:"inputIntroduction", placeholder: "郵便番号" %></td>
                        </tr>
                        <tr>
                            <th><label for="inputAddress">住所</label></th>
                            <td><%= f.text_field :address, autofocus: true, id:"inputAddress", placeholder: "住所" %></td>
                        </tr>
                        <tr>
                            <th><label for="inputTelephoneNumber">電話番号</label></th>
                            <td>
                               <%= f.text_field :telephone_number, autofocus: true, id:"inputTelephoneNumber", placeholder: "電話番号" %>
                            </td>
                        </tr>
                        <tr>
                            <th><label for="inputEmail">メールアドレス</label></th>
                            <td>
                               <%= f.email_field :email, autofocus: true, id:"inputEmail", placeholder: "メールアドレス" %>
                            </td>
                        </tr>
                        <tr>
                            <th><label for="inputEmail">会員ステータス</label></th>
                            <td>
                                <%= f.radio_button :is_active, true %>
                                <%= f.label :status, "有効" %>
                                
                                <%= f.radio_button :is_active, false %>
                                <%= f.label :status, "退会" %>
                            </td>
                        </tr>
                    </table>
                    <div class="text-center">
                        <%= f.submit "保存", class: "btn btn-primary mb-5" %>
                    </div>
                <% end %>
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container-fluid">
    <div style="height: 500px;" class ="row">
        
        <div class="col-md-2 offset-md-1 bg-danger">
           <h3 class="mt-5 mb-4 bg-light rounded-pill text-center">会員一覧</h3> 
        </div>
        
        <div class="col-md-7 my-5">
            <table class="table">
                <tr class="table-warning">
                    <th>会員id</th>
                    <th>氏名</th>
                    <th width="20%">メールアドレス</th>
                    <th>ステータス</th>
                    <th></th>
                </tr>
                <% @customers.each do |customer| %>
                <tr>
                    <td><%= customer.id %></td>
                    <td>
                        <%= link_to admin_customer_path(customer.id) do %>
                            <%= customer.last_name %>
                            <%= customer.first_name %>
                        <% end %>
                    </td>
                    <td><%= customer.email %></td>
                    <td>
                        <% if customer.is_active == true %>
                            有効
                        <% elsif customer.is_active == false %>
                            退会
                        <% end %>
                    </td>
                    <td></td>
                </tr>
                <% end %>
            </table>
            <%= paginate @customers %>
        </div>
    </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container-fluid">
    
    <div class ="row">
        <div class="col-md-2 bg-danger">
            <h3 class="mt-5 bg-light rounded-pill text-center">会員情報</h3>
        </div>
        <div class="col-md-5 offset-md-2 py-5">
            <table class="table">
                <tr>
                    <th width="30%">氏名</th>
                    <td>
                        <%= @customer.last_name %> 
                        <%= @customer.first_name %>
                    </td>
                </tr>
                <tr>
                    <th>フリガナ</th>
                    <td>
                        <%= @customer.last_name_kana %> 
                        <%= @customer.first_name_kana %>
                    </td>
                </tr>
                <tr>
                    <th>郵便番号</th>
                    <td><%= @customer.postal_code %></td>
                </tr>
                <tr>
                    <th>住所</th>
                    <td><%= @customer.address %></td>
                </tr>
                <tr>
                    <th>電話番号</th>
                    <td><%= @customer.telephone_number %></td>
                </tr>
                <tr>
                    <th>メールアドレス</th>
                    <td><%= @customer.email %></td>
                </tr>
                 <tr>
                    <th>会員ステータス</th>
                    <td>
                        <% if @customer.is_active == true %>
                        有効
                        <% elsif @customer.is_active == false %>
                        退会
                        <% end %>
                    </td>
                </tr>
                
            </table>
            <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "btn btn-primary" %>
        </div>
        <div class="col-md-2">
        </div>
    </div>
</div>

app/views/admin/genres/edit.html.erb
<div class="container-fluid">
    <div style="height: 500px;" class="row">
        <div class="col-md-2 offset-md-1 bg-danger">
          <h3 class="mt-5  bg-light rounded-pill text-center">ジャンル一覧</h3> 
        </div>
        <div class="col-md-6 pt-5">
        <%= form_with model: @genre, url: admin_genre_path(@genre), method: :patch, local: true do |f| %>
            <table class="table">
                <tr>
                    <th><label for="inputGenre">ジャンル</label></th>
                    <td><%= f.text_field :name, autofocus: true, id:"inputGenre" %></td>
                    <td><%= f.submit '変更を保存',class: "btn btn-primary" %></td>
                </tr>
            </table>
        <% end %> 

        </div>
    </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container-fluid">
    <div  class="row">
        <div class="col-md-2 offset-md-1 bg-danger">
          <h3 class="mt-5  bg-light rounded-pill text-center">ジャンル一覧</h3> 
        </div>
        <div class="col-md-6 pt-5">
        <%= form_with model: @genre, url: admin_genres_path, method: :post, local: true do |f| %>
            <table class="table">
                <tr>
                    <th>ジャンル</th>
                    <td><%= f.text_field :name %></td>
                    <td><%= f.submit '新規登録',class: "btn btn-primary" %></td>
                </tr>
            </table>
        <% end %> 
        
        <table class="table">
            <tr>
                <th>ジャンル</th>
                <td></td>
            </tr>
            <% @genres.each do |genre| %>
            <tr>
                <th><%= genre.name %></th>
                <td>
                    <%= link_to "編集", edit_admin_genre_path(genre), class: "btn btn-primary" %>
                </td>
            </tr>
            <% end %>
        </table>
        <%= paginate @genres %>
        </div>
    </div>
</div>

app/views/admin/homes/top.html.erb
<div class="container-fluid">
    
    <div style="height: 500px;" class="row">
        <div class="col-md-2 offset-md-1 bg-danger">
            <h3 class="mt-5 bg-light rounded-pill text-center">注文履歴一覧</h3>
        </div>
        <div class="col-md-8 pt-5">
            <table class="table">
                <tr>
                   <th>購入日時</th>
                   <th>注文者</th>
                   <th>注文個数</th>
                   <th>注文ステータス</th>
                </tr>
                <% @orders.each do |order| %>
                    <tr>
                        <td>
                            <%= link_to admin_order_path(order) do %>
                                <%= order.created_at.strftime('%y/%m/%d') %>
                            <% end %>
                            </td>
                        <td>
                            <%= order.customer.last_name %><%= order.customer.first_name %>
                        </td>
                        <% @total_amount = order.order_items.sum(:amount) %>
                        <td><%= @total_amount %></td>
                        <td><%= order.is_active %></td>
                    </tr>
                <% end %>
            </table>
            <%= paginate @orders %>
        </div>
        </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2 offset-md-1 bg-danger">
          <h3 class="mt-5  bg-light rounded-pill text-center">商品編集</h3> 
        </div>
        <div class="col-md-８ offset-md-1 pt-5">
            <div>
                <%= form_with model: [:admin, @item], local: true do |f| %>
                    <table class="table">
                        <tr>
                            <th>
                                <label for="inputImage">商品画像</label>
                            </th>
                            <td>
                                <%= attachment_image_tag @item, :image, :fill, 60, 60 %>
                                <%= f.attachment_field :image, placeholder: "プロフィール画像" %></td>
                        </tr>
                        <tr>
                            <th>
                                <label for="inputName">商品名</label>
                            </th>
                            <td><%= f.text_field :name, autofocus: true, id:"inputName", placeholder: "商品名" %></td>
                        </tr>
                        <tr>
                            <th><label for="inputIntroduction">商品説明</label></th>
                            <td><%= f.text_field :introduction, autofocus: true, id:"inputIntroduction", placeholder: "商品説明" %></td>
                        </tr>
                        <tr>
                            <th><label for="inputGenre">ジャンル</label></th>
                            <td></td>
                        </tr>
                        <tr>
                            <th><label for="inputPrice">税抜価格</label></th>
                            <td>
                               <%= f.text_field :price, autofocus: true, id:"inputPrice", placeholder: "税抜価格" %>
                            </td>
                        </tr>
                        <tr>
                           <th><label for="inputIsActiv">販売ステータス</label></th>
                           <td>
                               <%= f.radio_button :active_option, 0, checked: "checked" %>
                               <%= f.label :active_option, "販売中" %>

                               <%= f.radio_button :active_option, 1 %>
                               <%= f.label :active_option, "販売停止" %>

                               <%= f.radio_button :active_option, 2 %>
                               <%= f.label :active_option, "売切れ" %>

                           </td>
                        </tr>
                    </table>
                    <div class="text-center mb-5">
                        <%= f.submit "保存", class: "btn btn-primary" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/admin/items/index.html.erb
<div class="container-fluid">
    <div class="row ">
        <div class="col-md-2 offset-md-1 bg-danger">
            <h3 class="mt-5 bg-light rounded-pill text-center">商品一覧</h3>
        </div>
        <div class="col-md-6 offset-md-1 py-5">
            
            <%= link_to new_admin_item_path, class: "d-flex flex-row-reverse pb-3" do %>
                <i class="far fa-plus-square fa-2x"></i>
            <% end %>
            
       <table class="table">
            <tr>
               <th>商品ID</th>
               <th>商品名</th>
               <th>税抜価格</th>
               <th>ジャンル</th>
               <th>ステータス</th>
            </tr>
            <% @items.each do |item| %>
                <tr>
                    <td><%= item.id %></td>
                    <td>
                        <%= link_to admin_item_path(item), class: "btn btn-dark" do %>
                            <%= item.name %>
                        <% end %>
                    </td>
                    <td><%= item.price %></td>
                    <td><%= item.genre_id %></td>
                    <td><%= item.is_active %></td>
                </tr>
            <% end %>
       </table>
       <div class="d-flex justify-content-center"><%= paginate @items %></div>
    </div>
</div>

app/views/admin/items/new.html.erb
<div class="container-fluid">
    <div style="height: 500px;" class="row">
        <div class="col-md-2 offset-md-1 bg-danger">
          <h3 class="mt-5  bg-light rounded-pill text-center">会員情報編集</h3> 
        </div>
        <div class="col-md-6 pt-5">
        <%= form_with model: @item, url: admin_items_path, method: :post, local: true do |f| %>
        <table class="table">
            <tr>
                <th>商品画像</th>
                <td><%= f.attachment_field :image %></td>
            </tr>
            <tr>
                <th>商品名</th>
                <td><%= f.text_field :name %></td>
            </tr>
            <tr>
                <th>説明</th>
                <td><%= f.text_area :introduction %></td>
            </tr>
            <tr>
                <th>値段</th>
                <td><%= f.text_field :price %></td>
            </tr>
        </table>

            <div class="text-center">
                 <%= f.submit '保存',class: "btn btn-primary" %>  
            </div>
            
        <% end %>    
        </div>
    </div>
</div>

app/views/admin/items/show.html.erb
<div class="container-fluid">
    
    <div style="height:500px;" class ="row">
        <div class="col-md-2 offset-md-1 bg-danger">
            <h3 class="mt-5 bg-light rounded-pill text-center">商品詳細</h3>
        </div>
        <div class="col-md-3 pt-5 mt-5">
            <%= attachment_image_tag @item, :image, :fill, 300, 300 %>
        </div>
        <div class="col-md-4 mt-5">
            <table class="table">
                <tr>
                    <th>商品名</th>
                    <td><%= @item.name %></td>
                </tr>
                <tr>
                    <th>商品説明</th>
                    <td><%= @item.introduction %></td>
                </tr>
                <tr>
                    <th>ジャンル</th>
                    <td></td>
                </tr>
                <tr>
                    <th>
                       税込価格<br/>
                       (税抜価格)
                    </th>
                    <td>
                       <%= (@item.price*1.1).floor %><span class="pl-1">(</span><%=  @item.price %><span>)</span>
                    </td>
                </tr>
                <tr>
                   <th>販売ステータス</th>
                   <td><%= @item.is_active %></td>
                </tr>
            </table>
            <div class="text-center">
                <%= link_to "戻る", admin_items_path, class:"btn btn-primary" %>
                <%= link_to "編集する", edit_admin_item_path, class:"btn btn-warning" %>
            </div>
            
        </div>
        <div class="col-md-2">
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 <header>
    <nav class="navbar-right">
      <div class="container-fluid bg-danger py-4">
        <div class="row bd-highlight py-3" style="background-color: white; width:1000px,">
          <div class="col-md-3 bg-dark rounded-pill pl-3">
            <%= link_to root_path, class: "text-white text-decoration-none" do %>
              <h1>Nagano Cake</h1>
            <% end %>
          </div>
          <% if customer_signed_in? %>
            <div class="col-md-5 offset-md-4">
              <ul class="nav navbar-right nav-pills mb-3" id="pills-tab" role="tablist">
                <li class="nav-item">
                  <%= link_to mypage_path, class: "nav-link bg-dark text-white rounded-pill" do %>
                    <i class="fas fa-house-user"></i> マイページ
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to items_path, class: "nav-link bg-dark text-white rounded-pill" do %>
                    <i class="fas fa-cheese"></i> 商品一覧
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to cart_items_path, class: "nav-link bg-dark text-white rounded-pill" do %>
                    <i class="fas fa-shopping-cart"></i> カート
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_customer_session_path, method: :delete, class: "nav-link bg-dark text-white rounded-pill" do %>
                    <i class="fas fa-sign-out-alt"></i>　ログアウト
                  <% end %>
                </li>
              </ul>
            </div>
          <% elsif admin_signed_in? %>
            <div class="col-md-6 offset-md-3">
              <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
                <li class="nav-item">
                  <%= link_to admin_items_path, class: "nav-link bg-dark text-white rounded-pill" do %>
                    <i class="fas fa-cheese"></i> 商品一覧
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to admin_customers_path, class: "nav-link bg-dark text-white rounded-pill" do %>
                    <i class="fab fa-readme"></i>　会員一覧
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to admin_top_path, class: "nav-link bg-dark text-white rounded-pill" do %>
                    <i class="fab fa-readme"></i>　注文一覧
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to admin_genres_path, class: "nav-link bg-dark text-white rounded-pill" do %>
                    <i class="fas fa-file-signature"></i> ジャンル一覧
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link bg-dark text-white rounded-pill" do %>
                  <i class="fas fa-sign-out-alt"></i> ログアウト
                  <% end %>
                </li>
              </ul>
            </div>
          <% else %>
            <div class="col-md-5 offset-md-4">
              <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
                <li class="nav-item">
                  <%= link_to about_path, class: "nav-link bg-dark text-white rounded-pill" do %>
                    <i class="fab fa-readme"></i>　About
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to items_path, class: "nav-link bg-dark text-white rounded-pill" do %>
                    <i class="fas fa-cheese"></i> 商品一覧
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_customer_registration_path, class: "nav-link bg-dark text-white rounded-pill" do %>
                    <i class="fas fa-file-signature"></i> 新規登録
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_customer_session_path, class: "nav-link bg-dark text-white rounded-pill" do %>
                    <i class="fas fa-sign-in-alt"></i> ログイン
                  <% end %>
                </li>
              </ul>
            </div>
          <% end %>
        </div>
      </div>
    </nav>
  </header>

  <body>
    <%= yield %>
  </body>
  <fotter>
    <div class="py-4 bg-danger text-center">
      <h5 style=" background-color: white;" class="py-1" >©copy-right︎</h5>
    </div>
  </fotter>
</html>